import eslint from "@eslint/js";
import globals from "globals";
import pluginVue from "eslint-plugin-vue";
import tseslint from "typescript-eslint";
import vueParser from "vue-eslint-parser";

export default tseslint.config(
  {
    ignores: [
      "**/.claude/worktrees/**",
      "**/dist/**",
      // Generated by scripts/build-testplay.sh (includes the bundled Vue app under app/).
      "apps/worker/public/**",
      "**/coverage/**",
      "**/.wrangler/**",
      "**/.stryker-tmp/**",
      "apps/worker/worker-configuration.d.ts",
      "**/*.config.*",
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...pluginVue.configs["flat/recommended"],
  // 整形はPrettierに任せる。eslint-plugin-vueのレイアウト系ルールはPrettierと衝突する。
  { rules: pluginVue.configs["no-layout-rules"].rules },
  {
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        project: "./tsconfig.eslint.json",
        tsconfigRootDir: import.meta.dirname,
        extraFileExtensions: [".vue"],
      },
    },
    rules: {
      complexity: ["error", 8],
      "max-depth": ["error", 3],
      "max-params": ["error", 4],
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-unsafe-type-assertion": "error",
    },
  },
  {
    // SFCのscriptはvue-eslint-parserが取り出し、TypeScriptとして型情報つきで解析する。
    files: ["**/*.vue"],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tseslint.parser,
        sourceType: "module",
      },
    },
  },
  {
    // domainとcontentはUIフレームワークに依存しない（docs/development-harness.md の依存方向）。
    files: ["packages/domain/**/*.ts", "packages/content/**/*.ts"],
    rules: {
      "no-restricted-imports": ["error", { patterns: ["vue", "vue/*", "@vue/*"] }],
    },
  },
  {
    // domainはcontentを読むので、contentからdomainをimportすると循環になる。
    // 上のブロックと同じルール名なので、Vueの禁止もここで繰り返す（後のブロックが上書きする）。
    files: ["packages/content/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            "vue",
            "vue/*",
            "@vue/*",
            "@hell-ict/domain",
            "@hell-ict/domain/*",
            "**/domain/**",
          ],
        },
      ],
    },
  },
  {
    // system prompt とテスト用の正解は index から出さず、サブパスでだけ読める。
    // web がバンドルに入れたり、domain の判定が答えに依存したりしないよう、import を禁じる。
    // domain の行は上の Vue の禁止を上書きするので、ここで繰り返す。
    files: ["packages/domain/src/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            "vue",
            "vue/*",
            "@vue/*",
            "@hell-ict/content/prompts",
            "@hell-ict/content/answers",
            "**/content/src/prompts*",
            "**/content/src/answers*",
          ],
        },
      ],
    },
  },
  {
    // web のテストはバンドルに入らないので、提出例として answers を読んでよい。
    files: ["apps/web/**"],
    ignores: ["apps/web/test/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            "@hell-ict/content/prompts",
            "@hell-ict/content/answers",
            "**/content/src/prompts*",
            "**/content/src/answers*",
          ],
        },
      ],
    },
  },
  {
    // worker は system prompt を注入するが、テスト用の正解は読まない。
    files: ["apps/worker/src/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        { patterns: ["@hell-ict/content/answers", "**/content/src/answers*"] },
      ],
    },
  },
  {
    // The model bench runs on Node (type stripping) and has its own tsconfig for `.ts` imports.
    files: ["scripts/ai-bench/**/*.ts"],
    languageOptions: {
      globals: globals.node,
      parserOptions: { project: "./scripts/ai-bench/tsconfig.json" },
    },
  },
  {
    files: [
      "apps/worker/**/*.ts",
      "**/*.test.ts",
      "**/*.spec.ts",
      "packages/domain/test/**/*.ts",
      "apps/web/test/**/*.ts",
      "e2e/**/*.ts",
      "e2e/**/*.mjs",
      "scripts/**/*.mjs",
    ],
    languageOptions: {
      globals: globals.node,
      parserOptions: {
        project: false,
      },
    },
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    files: ["**/*.js", "**/*.mjs"],
    extends: [tseslint.configs.disableTypeChecked],
  },
);
